Repository AY2223S1-CS2103T-T12-2/tp, pull requests merged in 2022-10, with the labels that each got.

#48 Rename `list` command to `list_contact` command
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/test/java/swift/logic/LogicManagerTest.java
  src/test/java/swift/logic/commands/ListCommandTest.java
  src/test/java/swift/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#54 :memo: Docs: amend `codecov` ReadME
  README.md
Labels: type.Task, priority.High

#55 Docs: update index page
  docs/index.md
Labels: type.Task, priority.High

#52 ✨ Add `delete_task` command
  src/main/java/swift/commons/core/Messages.java
  src/main/java/swift/logic/commands/DeleteTaskCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/CliSyntax.java
  src/main/java/swift/logic/parser/DeleteTaskCommandParser.java
  src/main/java/swift/model/Model.java
  src/main/java/swift/model/ModelManager.java
  src/test/java/swift/logic/commands/AddCommandTest.java
  src/test/java/swift/logic/commands/AddTaskCommandTest.java
  src/test/java/swift/logic/commands/CommandTestUtil.java
  src/test/java/swift/logic/commands/DeleteCommandTest.java
  src/test/java/swift/logic/commands/DeleteTaskCommandTest.java
  src/test/java/swift/logic/commands/EditCommandTest.java
  src/test/java/swift/logic/commands/ListCommandTest.java
  src/test/java/swift/logic/parser/AddressBookParserTest.java
  src/test/java/swift/logic/parser/DeleteCommandParserTest.java
  src/test/java/swift/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/swift/logic/parser/EditCommandParserTest.java
  src/test/java/swift/logic/parser/ParserUtilTest.java
  src/test/java/swift/model/AddressBookTest.java
  src/test/java/swift/testutil/TypicalPersonIndexes.java
  src/test/java/swift/testutil/TypicalTaskIndexes.java
Labels: type.Story, priority.High

#58 Add `find_task` command
  src/main/java/swift/commons/core/Messages.java
  src/main/java/swift/logic/commands/FindContactCommand.java
  src/main/java/swift/logic/commands/FindTaskCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/FindContactCommandParser.java
  src/main/java/swift/logic/parser/FindTaskCommandParser.java
  src/main/java/swift/model/person/PersonNameContainsKeywordsPredicate.java
  src/main/java/swift/model/task/Task.java
  src/main/java/swift/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/java/swift/logic/commands/CommandTestUtil.java
  src/test/java/swift/logic/commands/FindContactCommandTest.java
  src/test/java/swift/logic/commands/FindTaskCommandTest.java
  src/test/java/swift/logic/parser/AddressBookParserTest.java
  src/test/java/swift/logic/parser/FindContactCommandParserTest.java
  src/test/java/swift/logic/parser/FindTaskCommandParserTest.java
  src/test/java/swift/model/ModelManagerTest.java
  src/test/java/swift/model/person/PersonNameContainsKeywordsPredicateTest.java
  src/test/java/swift/model/task/TaskNameContainsKeywordsPredicateTest.java
Labels: type.Story, priority.Medium

#57 Enhance Base UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#62 Refactor `Edit` command to `EditContact`
  .gitignore
  .vscode/settings.json
  docs/UserGuide.md
  docs/team/jasonqiu212.md
  docs/team/peppapighs.md
  src/main/java/swift/logic/commands/EditContactCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/EditContactCommandParser.java
  src/test/java/swift/logic/commands/CommandTestUtil.java
  src/test/java/swift/logic/commands/EditContactCommandTest.java
  src/test/java/swift/logic/commands/EditPersonDescriptorTest.java
  src/test/java/swift/logic/commands/ListContactCommandTest.java
  src/test/java/swift/logic/parser/AddressBookParserTest.java
  src/test/java/swift/logic/parser/EditContactCommandParserTest.java
  src/test/java/swift/testutil/EditPersonDescriptorBuilder.java
  src/test/java/swift/testutil/PersonUtil.java
Labels: type.Story, priority.High

#64 ✨ Fix: change edit command to edit_contact command
  src/main/java/swift/logic/commands/EditContactCommand.java
Labels: type.Story, priority.High

#77 Fix: remove white background of cell labels
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.High

#79 Add DG for Person-Task Bridge Relation
  .vscode/settings.json
  docs/DeveloperGuide.md
  docs/images/PersonTaskBridgeDiagram.png
Labels: type.Task, priority.High

#81 Rename `delete` command to `delete_contact`
  build.gradle
  src/main/java/swift/MainApp.java
  src/main/java/swift/logic/commands/DeleteContactCommand.java
  src/main/java/swift/logic/parser/AddContactCommandParser.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/DeleteContactCommandParser.java
  src/test/java/swift/logic/LogicManagerTest.java
  src/test/java/swift/logic/commands/DeleteContactCommandTest.java
  src/test/java/swift/logic/parser/AddContactCommandParserTest.java
  src/test/java/swift/logic/parser/AddressBookParserTest.java
  src/test/java/swift/logic/parser/DeleteContactCommandParserTest.java
Labels: type.Task, priority.High

#82 Add implementation of `find_task` command in DG
  README.md
  docs/AboutUs.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/index.md
Labels: type.Task, priority.High

#84 Add Implementation of AutoComplete and Command Suggestion in DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#85 Add implementation of tasks main panel to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#91 Fix: fix bridges not loaded during startup
  src/main/java/swift/model/AddressBook.java
  src/main/java/swift/model/bridge/PersonTaskBridgeList.java
  src/test/java/swift/model/bridge/PersonTaskBridgeListTest.java
Labels: type.Bug, priority.High, severity.High

#94 Fix: use relative person index when adding task
  src/main/java/swift/logic/commands/AddTaskCommand.java
  src/test/java/swift/logic/commands/AddTaskCommandTest.java
Labels: type.Bug, priority.High, severity.High

#86 Feat: Add select contact command and UI
  codecov.yml
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/main/java/swift/MainApp.java
  src/main/java/swift/commons/core/Messages.java
  src/main/java/swift/logic/Logic.java
  src/main/java/swift/logic/LogicManager.java
  src/main/java/swift/logic/commands/AddTaskCommand.java
  src/main/java/swift/logic/commands/DeleteTaskCommand.java
  src/main/java/swift/logic/commands/EditContactCommand.java
  src/main/java/swift/logic/commands/EditTaskCommand.java
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/commands/ListTaskCommand.java
  src/main/java/swift/logic/commands/SelectContactCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/SelectContactCommandParser.java
  src/main/java/swift/model/AddressBook.java
  src/main/java/swift/model/Model.java
  src/main/java/swift/model/ModelManager.java
  src/main/java/swift/ui/MainWindow.java
  src/main/java/swift/ui/PersonTaskCard.java
  src/main/java/swift/ui/PersonTaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonTaskCard.fxml
  src/main/resources/view/PersonTaskListPanel.fxml
  src/test/java/swift/logic/commands/AddCommandTest.java
  src/test/java/swift/logic/commands/AddTaskCommandTest.java
  src/test/java/swift/logic/commands/CommandTestUtil.java
  src/test/java/swift/logic/commands/ListTaskCommandTest.java
  src/test/java/swift/logic/commands/SelectContactCommandTest.java
  src/test/java/swift/logic/parser/AddressBookParserTest.java
  src/test/java/swift/logic/parser/SelectContactCommandParserTest.java
  src/test/java/swift/model/ModelManagerTest.java
  src/test/java/swift/testutil/PersonBuilder.java
  src/test/java/swift/testutil/TaskBuilder.java
  src/test/java/swift/testutil/TypicalBridges.java
  src/test/java/swift/testutil/TypicalIntegratedAddressBook.java
  src/test/java/swift/testutil/TypicalPersons.java
  src/test/java/swift/testutil/TypicalTasks.java
Labels: type.Story, severity.High

#83 Add Autocomplete for commands
  src/main/java/swift/logic/commands/AddContactCommand.java
  src/main/java/swift/logic/commands/AddTaskCommand.java
  src/main/java/swift/logic/commands/ClearCommand.java
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/main/java/swift/logic/commands/DeleteContactCommand.java
  src/main/java/swift/logic/commands/DeleteTaskCommand.java
  src/main/java/swift/logic/commands/EditContactCommand.java
  src/main/java/swift/logic/commands/EditTaskCommand.java
  src/main/java/swift/logic/commands/ExitCommand.java
  src/main/java/swift/logic/commands/FindContactCommand.java
  src/main/java/swift/logic/commands/FindTaskCommand.java
  src/main/java/swift/logic/commands/HelpCommand.java
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/commands/ListTaskCommand.java
  src/main/java/swift/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/test/java/swift/logic/commands/CommandSuggestorTest.java
  src/test/java/swift/logic/commands/EditTaskDescriptorTest.java
Labels: type.Story, priority.High

#105 Fix: fix name of deadline fxml component
  docs/_includes/custom-head.html
  src/main/java/swift/logic/parser/AddTaskCommandParser.java
  src/main/java/swift/logic/parser/EditTaskCommandParser.java
  src/main/resources/view/TaskListCard.fxml
Labels: priority.High

#111 Feat: add tab switching for commands and associated contacts to tasks lists view
  docs/DeveloperGuide.md
  docs/tutorials/TracingCode.md
  src/main/java/swift/logic/Logic.java
  src/main/java/swift/logic/LogicManager.java
  src/main/java/swift/logic/commands/AddContactCommand.java
  src/main/java/swift/logic/commands/AddTaskCommand.java
  src/main/java/swift/logic/commands/ClearCommand.java
  src/main/java/swift/logic/commands/CommandResult.java
  src/main/java/swift/logic/commands/CommandType.java
  src/main/java/swift/logic/commands/DeleteContactCommand.java
  src/main/java/swift/logic/commands/DeleteTaskCommand.java
  src/main/java/swift/logic/commands/EditContactCommand.java
  src/main/java/swift/logic/commands/EditTaskCommand.java
  src/main/java/swift/logic/commands/ExitCommand.java
  src/main/java/swift/logic/commands/FindContactCommand.java
  src/main/java/swift/logic/commands/FindTaskCommand.java
  src/main/java/swift/logic/commands/HelpCommand.java
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/commands/ListTaskCommand.java
  src/main/java/swift/logic/commands/SelectContactCommand.java
  src/main/java/swift/logic/commands/SelectTaskCommand.java
  src/main/java/swift/model/Model.java
  src/main/java/swift/model/ModelManager.java
  src/main/java/swift/ui/MainWindow.java
  src/main/java/swift/ui/PersonTaskCard.java
  src/main/java/swift/ui/PersonTaskListPanel.java
  src/main/java/swift/ui/ResultDisplay.java
  src/main/java/swift/ui/TaskCard.java
  src/main/java/swift/ui/TaskListPanel.java
  src/main/java/swift/ui/TaskPersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PersonTaskCard.fxml
  src/main/resources/view/PersonTaskListPanel.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/main/resources/view/TaskPersonCard.fxml
  src/test/java/swift/logic/commands/AddCommandIntegrationTest.java
  src/test/java/swift/logic/commands/AddContactCommandTest.java
  src/test/java/swift/logic/commands/AddTaskCommandTest.java
  src/test/java/swift/logic/commands/ClearCommandTest.java
  src/test/java/swift/logic/commands/CommandResultTest.java
  src/test/java/swift/logic/commands/CommandTestUtil.java
  src/test/java/swift/logic/commands/DeleteContactCommandTest.java
  src/test/java/swift/logic/commands/DeleteTaskCommandTest.java
  src/test/java/swift/logic/commands/EditContactCommandTest.java
  src/test/java/swift/logic/commands/EditTaskCommandTest.java
  src/test/java/swift/logic/commands/ExitCommandTest.java
  src/test/java/swift/logic/commands/FindContactCommandTest.java
  src/test/java/swift/logic/commands/FindTaskCommandTest.java
  src/test/java/swift/logic/commands/HelpCommandTest.java
  src/test/java/swift/logic/commands/ListContactCommandTest.java
  src/test/java/swift/logic/commands/ListTaskCommandTest.java
  src/test/java/swift/logic/commands/SelectContactCommandTest.java
  src/test/java/swift/logic/commands/SelectTaskCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High

#117 Doc: add select commands into UG
  docs/UserGuide.md
Labels: type.Task

#113 Enhance Autocomplete and fix bugs
  src/main/java/swift/logic/commands/AddContactCommand.java
  src/main/java/swift/logic/commands/AddTaskCommand.java
  src/main/java/swift/logic/commands/ClearCommand.java
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/main/java/swift/logic/commands/DeleteContactCommand.java
  src/main/java/swift/logic/commands/DeleteTaskCommand.java
  src/main/java/swift/logic/commands/EditContactCommand.java
  src/main/java/swift/logic/commands/EditTaskCommand.java
  src/main/java/swift/logic/commands/ExitCommand.java
  src/main/java/swift/logic/commands/FindContactCommand.java
  src/main/java/swift/logic/commands/FindTaskCommand.java
  src/main/java/swift/logic/commands/HelpCommand.java
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/commands/ListTaskCommand.java
  src/main/java/swift/logic/commands/SelectContactCommand.java
  src/main/java/swift/logic/commands/SelectTaskCommand.java
  src/main/java/swift/logic/parser/ArgumentTokenizer.java
  src/main/java/swift/logic/parser/CliSyntax.java
  src/main/java/swift/logic/parser/Prefix.java
  src/main/resources/view/DarkTheme.css
  src/test/java/swift/logic/commands/CommandSuggestorTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High

#99 Feat: add assign command
  docs/UserGuide.md
  src/main/java/swift/logic/commands/AssignCommand.java
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/main/java/swift/logic/commands/CommandType.java
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/commands/ListTaskCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/AssignCommandParser.java
  src/main/java/swift/logic/parser/CliSyntax.java
  src/main/java/swift/ui/MainWindow.java
  src/test/java/swift/logic/commands/AssignCommandTest.java
  src/test/java/swift/logic/commands/ListTaskCommandTest.java
  src/test/java/swift/logic/parser/AssignCommandParserTest.java
Labels: type.Story, priority.High

#126 Style: update text font and tags style
  src/main/java/swift/ui/PersonCard.java
  src/main/java/swift/ui/PersonTaskCard.java
  src/main/java/swift/ui/TaskCard.java
  src/main/java/swift/ui/TaskPersonCard.java
  src/main/resources/fonts/Inter-Bold.ttf
  src/main/resources/fonts/Inter-Medium.ttf
  src/main/resources/fonts/Inter-Regular.ttf
  src/main/resources/fonts/Inter-SemiBold.ttf
  src/main/resources/fonts/SpaceGrotesk-Regular.ttf
  src/main/resources/images/address_icon.png
  src/main/resources/images/address_icon_2.png
  src/main/resources/images/email_icon.png
  src/main/resources/images/email_icon_2.png
  src/main/resources/images/phone_icon.png
  src/main/resources/images/phone_icon_2.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonTaskCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskPersonCard.fxml
Labels: type.Enhancement

#127 Feat: add `unassign` command
  docs/UserGuide.md
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/main/java/swift/logic/commands/CommandType.java
  src/main/java/swift/logic/commands/UnassignCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/UnassignCommandParser.java
  src/main/java/swift/model/AddressBook.java
  src/main/java/swift/model/Model.java
  src/main/java/swift/model/ModelManager.java
  src/main/java/swift/ui/MainWindow.java
  src/test/java/swift/logic/commands/AddContactCommandTest.java
  src/test/java/swift/logic/commands/AddTaskCommandTest.java
  src/test/java/swift/logic/commands/UnassignCommandTest.java
  src/test/java/swift/logic/parser/UnassignCommandParserTest.java
Labels: type.Story, priority.High

#124 Feat: add description to task list Ui
  src/main/java/swift/ui/TaskCard.java
  src/main/resources/view/PersonTaskCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: type.Task, priority.High

#128 Feat: Allow mark and unmark tasks
  docs/UserGuide.md
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/main/java/swift/logic/commands/EditTaskCommand.java
  src/main/java/swift/logic/commands/MarkTaskCommand.java
  src/main/java/swift/logic/commands/UnmarkTaskCommand.java
  src/main/java/swift/logic/parser/AddressBookParser.java
  src/main/java/swift/logic/parser/CliSyntax.java
  src/main/java/swift/logic/parser/MarkTaskCommandParser.java
  src/main/java/swift/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/swift/model/task/Task.java
Labels: type.Story, priority.High

#132 Feat: add `isDone` for task to storage
  src/main/java/swift/logic/commands/AddTaskCommand.java
  src/main/java/swift/model/util/SampleDataUtil.java
  src/main/java/swift/storage/JsonAdaptedTask.java
Labels: type.Enhancement, priority.High

#133 📝 Docs: add user guide for clear command
  docs/UserGuide.md
  src/main/java/swift/logic/commands/AssignCommand.java
  src/main/java/swift/logic/commands/UnassignCommand.java
  src/main/java/swift/ui/MainWindow.java
Labels: type.Enhancement, priority.High

#134 Autocomplete enhancements
  docs/UserGuide.md
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/test/java/swift/logic/commands/CommandSuggestorTest.java
Labels: type.Enhancement, priority.Medium

#137 Feat: sort tasks by chronological order
  src/main/java/swift/model/ModelManager.java
  src/main/java/swift/model/task/Deadline.java
  src/main/java/swift/model/task/Task.java
  src/main/java/swift/model/task/TaskName.java
  src/test/java/swift/logic/commands/EditTaskCommandTest.java
  src/test/java/swift/logic/commands/FindTaskCommandTest.java
Labels: type.Enhancement, priority.Medium

#140 Menu bar Enhancements
  src/main/java/swift/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Medium, severity.Medium

#138 Style: add task icons
  src/main/java/swift/ui/TaskCard.java
  src/main/resources/images/check_icon.png
  src/main/resources/images/check_icon_2.png
  src/main/resources/images/checked.png
  src/main/resources/images/deadline_icon.png
  src/main/resources/images/deadline_icon_2.png
  src/main/resources/images/description_icon.png
  src/main/resources/images/description_icon_2.png
  src/main/resources/images/uncheck_icon.png
  src/main/resources/images/uncheck_icon_2.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: type.Enhancement

#142 Style: resize command box
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement

#144 Docs: update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/autocomplete.png
  docs/images/findAlexDavidResult.png
  docs/index.md
Labels: type.Task, priority.High

#145 Style: underline menu button
  src/main/java/swift/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Medium

#147 Perf: fix default window size
  src/main/java/swift/commons/core/GuiSettings.java
Labels: type.Task, priority.High

#148 Bug: Fix task tags display
  src/main/java/swift/ui/MainWindow.java
Labels: type.Bug, priority.High

#193 Update user guide
  README.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/images/Ui.png
  docs/images/user-guide/caution.png
  docs/images/user-guide/command-input-box.png
  docs/images/user-guide/contact-list.png
  docs/images/user-guide/contact-sidebar.png
  docs/images/user-guide/findAlexDavidResult.png
  docs/images/user-guide/menu-bar.png
  docs/images/user-guide/note.png
  docs/images/user-guide/search-results.png
  docs/images/user-guide/task-list.png
  docs/images/user-guide/task-sidebar.png
  docs/images/user-guide/tip.png
  docs/index.md
Labels: type.Task, priority.High

#191 Docs: update command descriptions involving displayed index
  docs/UserGuide.md
Labels: type.Task, priority.High

#190 Docs: separate commands by type in user guide
  docs/UserGuide.md
Labels: type.Task, priority.High
