Repository AY2223S1-CS2103T-T12-2/tp, pull requests merged in 2022-11, with the labels that each got.

#202 Add Jason's PPP draft
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/team/jasonqiu212.md
Labels: type.Task, priority.High

#204 Update Santosh's PPP
  docs/team/santosh3007.md
Labels: type.Task

#211 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/initialize.scss
  docs/_sass/toc.scss
  docs/assets/css/style.scss
  docs/images/user-guide/contact-list.png
  docs/images/user-guide/contact-sidebar.png
  docs/images/user-guide/note.png
  docs/images/user-guide/task-list.png
  docs/images/user-guide/task-sidebar.png
Labels: type.Task, priority.High

#214 Docs: update PersonTaskBridge DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PersonTaskBridgeDiagram.puml
  docs/images/PersonTaskBridgeDiagram.png
  docs/team/jasonqiu212.md
  docs/team/santosh3007.md
  docs/team/shenyicui.md
  docs/team/yunruu.md
Labels: type.Task

#217 Fix: make context menu fields visible
  src/main/resources/view/DarkTheme.css
Labels: type.Bug

#219 Autocomplete Fixes
  src/main/java/swift/logic/commands/CommandSuggestor.java
  src/main/java/swift/ui/CommandBox.java
  src/main/resources/view/DarkTheme.css
  src/test/java/swift/logic/commands/MarkTaskCommandTest.java
  src/test/java/swift/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/swift/testutil/EditTaskDescriptorBuilder.java
  src/test/java/swift/testutil/TaskBuilder.java
Labels: type.Bug, priority.High

#220 :bug: Fix: task equality
  src/main/java/swift/model/task/Task.java
Labels: type.Bug, priority.High

#212 Fix: show all tasks and contacts after `list_contact` and `list_task`
  docs/UserGuide.md
  src/main/java/swift/logic/commands/ListContactCommand.java
  src/main/java/swift/logic/commands/ListTaskCommand.java
  src/main/java/swift/logic/commands/SelectContactCommand.java
  src/main/java/swift/logic/commands/SelectTaskCommand.java
Labels: priority.High

#226 Fix: command output box header
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#230 Fix: early truncation of task name bug
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug

#237 Fix backspace bug
  src/main/java/swift/ui/CommandBox.java
Labels: severity.Low

#242 Update DG
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/images/user-guide/command-results.png
  docs/images/user-guide/search-results.png
Labels: type.Task, priority.High

#241 Add caution note for `clear` command
  docs/UserGuide.md
Labels: priority.Low
